import React, { useState, useEffect } from 'react';
import { getCourseSummary } from '../lib/api.js';

const AISummary = ({ courseId, data }) => {
  const [summary, setSummary] = useState(data);
  const [loading, setLoading] = useState(!data);
  const [isExpanded, setIsExpanded] = useState(false);

  useEffect(() => {
    if (!summary && courseId) {
      const loadSummary = async () => {
        const result = await getCourseSummary(courseId);
        setSummary(result);
        setLoading(false);
      };
      loadSummary();
    }
  }, [courseId, summary]);

  if (loading) {
    return (
      <div className="space-y-4 animate-pulse">
        <div className="h-4 bg-slate-200 rounded w-3/4"></div>
        <div className="h-4 bg-slate-200 rounded w-full"></div>
        <div className="h-4 bg-slate-200 rounded w-5/6"></div>
      </div>
    );
  }

  if (!summary) return null;

  return (
    <div className="space-y-6">
      <div>
        <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-3">Key Outcomes</h4>
        <ul className="grid grid-cols-1 gap-2">
          {summary.outcomes?.map((outcome, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
              <span className="text-emerald-500 mt-1">✓</span>
              {outcome}
            </li>
          ))}
        </ul>
      </div>

      <div>
        <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-2">Study Plan</h4>
        <p className={`text-sm text-slate-700 leading-relaxed ${!isExpanded && 'line-clamp-3'}`}>
          {summary.study_plan}
        </p>
        <button 
          onClick={() => setIsExpanded(!isExpanded)}
          className="mt-2 text-emerald-600 text-xs font-bold hover:underline"
        >
          {isExpanded ? 'Show Less' : 'Read Full Plan'}
        </button>
      </div>

      <div className="bg-emerald-50 border border-emerald-100 p-4 rounded-lg">
        <h4 className="text-xs font-bold text-emerald-800 uppercase tracking-wider mb-1">Verdict</h4>
        <p className="text-sm text-emerald-900 font-medium">{summary.verdict}</p>
      </div>
      
      <div className="text-[10px] text-slate-400 text-right italic">
        Generated by Claude AI • Completion: {summary.estimated_completion_weeks} weeks
      </div>
    </div>
  );
};

export default AISummary;
